// Code generated by protoc-gen-go-fluffycore-di. DO NOT EDIT.
// Code generated grpcGateway

package helloworld

import (
	context "context"
	sync "sync"

	fluffy_dozm_di "github.com/fluffy-bunny/fluffy-dozm-di"
	GRPCClientFactory "github.com/fluffy-bunny/fluffycore/contracts/GRPCClientFactory"
	endpoint "github.com/fluffy-bunny/fluffycore/contracts/endpoint"
	tokensource "github.com/fluffy-bunny/fluffycore/contracts/tokensource"
	grpcclient "github.com/fluffy-bunny/fluffycore/grpcclient"
	dicontext "github.com/fluffy-bunny/fluffycore/middleware/dicontext"
	runtime "github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	grpc "google.golang.org/grpc"
)

// IAppGreeterClientAccessor defines the grpc client
type IAppGreeterClientAccessor interface {
	GetClient() (GreeterClient, error)
}

// AppGreeterClientAccessorConfig defines the grpc client struct
type AppGreeterClientAccessorConfig struct {
	Url string
}

// AppGreeterClientAccessor defines the grpc client struct
type AppGreeterClientAccessor struct {
	rwLock            sync.RWMutex
	config            *AppGreeterClientAccessorConfig
	appTokenSource    tokensource.IAppTokenSource
	grpcClientFactory GRPCClientFactory.IGRPCClientFactory
	client            GreeterClient
}

var stemAppGreeterClientAccessor = (*AppGreeterClientAccessor)(nil)
var _ IAppGreeterClientAccessor = stemAppGreeterClientAccessor

func (s *AppGreeterClientAccessor) Ctor(
	config *AppGreeterClientAccessorConfig,
	appTokenSource tokensource.IAppTokenSource,
	grpcClientFactory GRPCClientFactory.IGRPCClientFactory,
) (IAppGreeterClientAccessor, error) {
	return &AppGreeterClientAccessor{
		config:            config,
		appTokenSource:    appTokenSource,
		grpcClientFactory: grpcClientFactory,
	}, nil
}

// AddSingletonIAppGreeterClientAccessor ...
func AddSingletonIAppGreeterClientAccessor(
	cb fluffy_dozm_di.ContainerBuilder,
	config *AppGreeterClientAccessorConfig,
) {
	fluffy_dozm_di.AddInstance[*AppGreeterClientAccessorConfig](cb, config)
	fluffy_dozm_di.AddSingleton[IAppGreeterClientAccessor](cb, stemAppGreeterClientAccessor.Ctor)
}

func (s *AppGreeterClientAccessor) GetClient() (GreeterClient, error) {
	doGetClient := func() GreeterClient {
		s.rwLock.RLock()
		defer s.rwLock.RUnlock()
		if s.client != nil {
			return s.client
		}
		return nil
	}

	client := doGetClient()
	if client != nil {
		return client, nil
	}

	tokenSource, err := s.appTokenSource.GetTokenSource()
	if err != nil {
		return nil, err
	}
	//--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--
	s.rwLock.Lock()
	defer s.rwLock.Unlock()
	//--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--

	grpcClient, err := s.grpcClientFactory.NewGrpcClient(
		grpcclient.WithTarget(s.config.Url),
		grpcclient.WithTokenSource(tokenSource),
		grpcclient.WithInsecure(true), // TODO: remove this in production
	)
	if err != nil {
		return nil, err
	}
	s.client = NewGreeterClient(grpcClient.GetConnection())
	return s.client, nil
}

// IFluffyCoreGreeterServer defines the grpc server
type IFluffyCoreGreeterServer interface {
	GreeterServer
}

type UnimplementedFluffyCoreGreeterServerEndpointRegistration struct {
}

func (UnimplementedFluffyCoreGreeterServerEndpointRegistration) RegisterFluffyCoreHandler(gwmux *runtime.ServeMux, conn *grpc.ClientConn) {
}

// GreeterFluffyCoreServer defines the grpc server truct
type GreeterFluffyCoreServer struct {
	UnimplementedGreeterServer
	UnimplementedFluffyCoreGreeterServerEndpointRegistration
}

// RegisterFluffyCoreGRPCService the server with grpc
func (srv *GreeterFluffyCoreServer) RegisterFluffyCoreGRPCService(s *grpc.Server) {
	RegisterGreeterServer(s, srv)
}

// AddGreeterServerWithExternalRegistration adds the fluffycore aware grpc server and external registration service.  Mainly used for grpc-gateway
func AddGreeterServerWithExternalRegistration(cb fluffy_dozm_di.ContainerBuilder, ctor any, register func() endpoint.IEndpointRegistration) {
	fluffy_dozm_di.AddSingleton[endpoint.IEndpointRegistration](cb, register)
	fluffy_dozm_di.AddScoped[IFluffyCoreGreeterServer](cb, ctor)
}

// AddGreeterServer adds the fluffycore aware grpc server
func AddGreeterServer(cb fluffy_dozm_di.ContainerBuilder, ctor any) {
	AddGreeterServerWithExternalRegistration(cb, ctor, func() endpoint.IEndpointRegistration {
		return &GreeterFluffyCoreServer{}
	})
}

// SayHello...
func (s *GreeterFluffyCoreServer) SayHello(ctx context.Context, request *HelloRequest) (*HelloReply, error) {
	requestContainer := dicontext.GetRequestContainer(ctx)
	downstreamService := fluffy_dozm_di.Get[IFluffyCoreGreeterServer](requestContainer)
	return downstreamService.SayHello(ctx, request)
}

// SayHelloAuth...
func (s *GreeterFluffyCoreServer) SayHelloAuth(ctx context.Context, request *HelloRequest) (*HelloReply, error) {
	requestContainer := dicontext.GetRequestContainer(ctx)
	downstreamService := fluffy_dozm_di.Get[IFluffyCoreGreeterServer](requestContainer)
	return downstreamService.SayHelloAuth(ctx, request)
}

// SayHelloDownstream...
func (s *GreeterFluffyCoreServer) SayHelloDownstream(ctx context.Context, request *HelloRequest) (*HelloReply, error) {
	requestContainer := dicontext.GetRequestContainer(ctx)
	downstreamService := fluffy_dozm_di.Get[IFluffyCoreGreeterServer](requestContainer)
	return downstreamService.SayHelloDownstream(ctx, request)
}

// IAppGreeter2ClientAccessor defines the grpc client
type IAppGreeter2ClientAccessor interface {
	GetClient() (Greeter2Client, error)
}

// AppGreeter2ClientAccessorConfig defines the grpc client struct
type AppGreeter2ClientAccessorConfig struct {
	Url string
}

// AppGreeter2ClientAccessor defines the grpc client struct
type AppGreeter2ClientAccessor struct {
	rwLock            sync.RWMutex
	config            *AppGreeter2ClientAccessorConfig
	appTokenSource    tokensource.IAppTokenSource
	grpcClientFactory GRPCClientFactory.IGRPCClientFactory
	client            Greeter2Client
}

var stemAppGreeter2ClientAccessor = (*AppGreeter2ClientAccessor)(nil)
var _ IAppGreeter2ClientAccessor = stemAppGreeter2ClientAccessor

func (s *AppGreeter2ClientAccessor) Ctor(
	config *AppGreeter2ClientAccessorConfig,
	appTokenSource tokensource.IAppTokenSource,
	grpcClientFactory GRPCClientFactory.IGRPCClientFactory,
) (IAppGreeter2ClientAccessor, error) {
	return &AppGreeter2ClientAccessor{
		config:            config,
		appTokenSource:    appTokenSource,
		grpcClientFactory: grpcClientFactory,
	}, nil
}

// AddSingletonIAppGreeter2ClientAccessor ...
func AddSingletonIAppGreeter2ClientAccessor(
	cb fluffy_dozm_di.ContainerBuilder,
	config *AppGreeter2ClientAccessorConfig,
) {
	fluffy_dozm_di.AddInstance[*AppGreeter2ClientAccessorConfig](cb, config)
	fluffy_dozm_di.AddSingleton[IAppGreeter2ClientAccessor](cb, stemAppGreeter2ClientAccessor.Ctor)
}

func (s *AppGreeter2ClientAccessor) GetClient() (Greeter2Client, error) {
	doGetClient := func() Greeter2Client {
		s.rwLock.RLock()
		defer s.rwLock.RUnlock()
		if s.client != nil {
			return s.client
		}
		return nil
	}

	client := doGetClient()
	if client != nil {
		return client, nil
	}

	tokenSource, err := s.appTokenSource.GetTokenSource()
	if err != nil {
		return nil, err
	}
	//--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--
	s.rwLock.Lock()
	defer s.rwLock.Unlock()
	//--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--

	grpcClient, err := s.grpcClientFactory.NewGrpcClient(
		grpcclient.WithTarget(s.config.Url),
		grpcclient.WithTokenSource(tokenSource),
		grpcclient.WithInsecure(true), // TODO: remove this in production
	)
	if err != nil {
		return nil, err
	}
	s.client = NewGreeter2Client(grpcClient.GetConnection())
	return s.client, nil
}

// IFluffyCoreGreeter2Server defines the grpc server
type IFluffyCoreGreeter2Server interface {
	Greeter2Server
}

type UnimplementedFluffyCoreGreeter2ServerEndpointRegistration struct {
}

func (UnimplementedFluffyCoreGreeter2ServerEndpointRegistration) RegisterFluffyCoreHandler(gwmux *runtime.ServeMux, conn *grpc.ClientConn) {
}

// Greeter2FluffyCoreServer defines the grpc server truct
type Greeter2FluffyCoreServer struct {
	UnimplementedGreeter2Server
	UnimplementedFluffyCoreGreeter2ServerEndpointRegistration
}

// RegisterFluffyCoreGRPCService the server with grpc
func (srv *Greeter2FluffyCoreServer) RegisterFluffyCoreGRPCService(s *grpc.Server) {
	RegisterGreeter2Server(s, srv)
}

// AddGreeter2ServerWithExternalRegistration adds the fluffycore aware grpc server and external registration service.  Mainly used for grpc-gateway
func AddGreeter2ServerWithExternalRegistration(cb fluffy_dozm_di.ContainerBuilder, ctor any, register func() endpoint.IEndpointRegistration) {
	fluffy_dozm_di.AddSingleton[endpoint.IEndpointRegistration](cb, register)
	fluffy_dozm_di.AddScoped[IFluffyCoreGreeter2Server](cb, ctor)
}

// AddGreeter2Server adds the fluffycore aware grpc server
func AddGreeter2Server(cb fluffy_dozm_di.ContainerBuilder, ctor any) {
	AddGreeter2ServerWithExternalRegistration(cb, ctor, func() endpoint.IEndpointRegistration {
		return &Greeter2FluffyCoreServer{}
	})
}

// SayHello...
func (s *Greeter2FluffyCoreServer) SayHello(ctx context.Context, request *HelloRequest) (*HelloReply2, error) {
	requestContainer := dicontext.GetRequestContainer(ctx)
	downstreamService := fluffy_dozm_di.Get[IFluffyCoreGreeter2Server](requestContainer)
	return downstreamService.SayHello(ctx, request)
}

// IAppMyStreamServiceClientAccessor defines the grpc client
type IAppMyStreamServiceClientAccessor interface {
	GetClient() (MyStreamServiceClient, error)
}

// AppMyStreamServiceClientAccessorConfig defines the grpc client struct
type AppMyStreamServiceClientAccessorConfig struct {
	Url string
}

// AppMyStreamServiceClientAccessor defines the grpc client struct
type AppMyStreamServiceClientAccessor struct {
	rwLock            sync.RWMutex
	config            *AppMyStreamServiceClientAccessorConfig
	appTokenSource    tokensource.IAppTokenSource
	grpcClientFactory GRPCClientFactory.IGRPCClientFactory
	client            MyStreamServiceClient
}

var stemAppMyStreamServiceClientAccessor = (*AppMyStreamServiceClientAccessor)(nil)
var _ IAppMyStreamServiceClientAccessor = stemAppMyStreamServiceClientAccessor

func (s *AppMyStreamServiceClientAccessor) Ctor(
	config *AppMyStreamServiceClientAccessorConfig,
	appTokenSource tokensource.IAppTokenSource,
	grpcClientFactory GRPCClientFactory.IGRPCClientFactory,
) (IAppMyStreamServiceClientAccessor, error) {
	return &AppMyStreamServiceClientAccessor{
		config:            config,
		appTokenSource:    appTokenSource,
		grpcClientFactory: grpcClientFactory,
	}, nil
}

// AddSingletonIAppMyStreamServiceClientAccessor ...
func AddSingletonIAppMyStreamServiceClientAccessor(
	cb fluffy_dozm_di.ContainerBuilder,
	config *AppMyStreamServiceClientAccessorConfig,
) {
	fluffy_dozm_di.AddInstance[*AppMyStreamServiceClientAccessorConfig](cb, config)
	fluffy_dozm_di.AddSingleton[IAppMyStreamServiceClientAccessor](cb, stemAppMyStreamServiceClientAccessor.Ctor)
}

func (s *AppMyStreamServiceClientAccessor) GetClient() (MyStreamServiceClient, error) {
	doGetClient := func() MyStreamServiceClient {
		s.rwLock.RLock()
		defer s.rwLock.RUnlock()
		if s.client != nil {
			return s.client
		}
		return nil
	}

	client := doGetClient()
	if client != nil {
		return client, nil
	}

	tokenSource, err := s.appTokenSource.GetTokenSource()
	if err != nil {
		return nil, err
	}
	//--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--
	s.rwLock.Lock()
	defer s.rwLock.Unlock()
	//--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--

	grpcClient, err := s.grpcClientFactory.NewGrpcClient(
		grpcclient.WithTarget(s.config.Url),
		grpcclient.WithTokenSource(tokenSource),
		grpcclient.WithInsecure(true), // TODO: remove this in production
	)
	if err != nil {
		return nil, err
	}
	s.client = NewMyStreamServiceClient(grpcClient.GetConnection())
	return s.client, nil
}

// IFluffyCoreMyStreamServiceServer defines the grpc server
type IFluffyCoreMyStreamServiceServer interface {
	MyStreamServiceServer
}

type UnimplementedFluffyCoreMyStreamServiceServerEndpointRegistration struct {
}

func (UnimplementedFluffyCoreMyStreamServiceServerEndpointRegistration) RegisterFluffyCoreHandler(gwmux *runtime.ServeMux, conn *grpc.ClientConn) {
}

// MyStreamServiceFluffyCoreServer defines the grpc server truct
type MyStreamServiceFluffyCoreServer struct {
	UnimplementedMyStreamServiceServer
	UnimplementedFluffyCoreMyStreamServiceServerEndpointRegistration
}

// RegisterFluffyCoreGRPCService the server with grpc
func (srv *MyStreamServiceFluffyCoreServer) RegisterFluffyCoreGRPCService(s *grpc.Server) {
	RegisterMyStreamServiceServer(s, srv)
}

// AddMyStreamServiceServerWithExternalRegistration adds the fluffycore aware grpc server and external registration service.  Mainly used for grpc-gateway
func AddMyStreamServiceServerWithExternalRegistration(cb fluffy_dozm_di.ContainerBuilder, ctor any, register func() endpoint.IEndpointRegistration) {
	fluffy_dozm_di.AddSingleton[endpoint.IEndpointRegistration](cb, register)
	fluffy_dozm_di.AddScoped[IFluffyCoreMyStreamServiceServer](cb, ctor)
}

// AddMyStreamServiceServer adds the fluffycore aware grpc server
func AddMyStreamServiceServer(cb fluffy_dozm_di.ContainerBuilder, ctor any) {
	AddMyStreamServiceServerWithExternalRegistration(cb, ctor, func() endpoint.IEndpointRegistration {
		return &MyStreamServiceFluffyCoreServer{}
	})
}

// RequestPoints...
func (s *MyStreamServiceFluffyCoreServer) RequestPoints(request *PointsRequest, stream MyStreamService_RequestPointsServer) error {
	ctx := stream.Context()
	requestContainer := dicontext.GetRequestContainer(ctx)
	downstreamService := fluffy_dozm_di.Get[IFluffyCoreMyStreamServiceServer](requestContainer)
	return downstreamService.RequestPoints(request, stream)
}

// StreamPoints...
func (s *MyStreamServiceFluffyCoreServer) StreamPoints(stream MyStreamService_StreamPointsServer) error {
	ctx := stream.Context()
	requestContainer := dicontext.GetRequestContainer(ctx)
	downstreamService := fluffy_dozm_di.Get[IFluffyCoreMyStreamServiceServer](requestContainer)
	return downstreamService.StreamPoints(stream)
}
