// Copyright 2015 gRPC authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/helloworld/helloworld.proto

package helloworld

import (
	_ "github.com/fluffy-bunny/fluffycore/nats/api/annotations"
	models "github.com/fluffy-bunny/fluffycore/proto/helloworld/models"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NestedMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrgId         string                 `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	Age           int32                  `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NestedMessage) Reset() {
	*x = NestedMessage{}
	mi := &file_proto_helloworld_helloworld_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NestedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NestedMessage) ProtoMessage() {}

func (x *NestedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_helloworld_helloworld_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NestedMessage.ProtoReflect.Descriptor instead.
func (*NestedMessage) Descriptor() ([]byte, []int) {
	return file_proto_helloworld_helloworld_proto_rawDescGZIP(), []int{0}
}

func (x *NestedMessage) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *NestedMessage) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

type ParentMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NestedMessage *NestedMessage         `protobuf:"bytes,1,opt,name=nested_message,json=nestedMessage,proto3" json:"nested_message,omitempty"`
	OrgId         string                 `protobuf:"bytes,2,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	Age           int32                  `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParentMessage) Reset() {
	*x = ParentMessage{}
	mi := &file_proto_helloworld_helloworld_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParentMessage) ProtoMessage() {}

func (x *ParentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_helloworld_helloworld_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParentMessage.ProtoReflect.Descriptor instead.
func (*ParentMessage) Descriptor() ([]byte, []int) {
	return file_proto_helloworld_helloworld_proto_rawDescGZIP(), []int{1}
}

func (x *ParentMessage) GetNestedMessage() *NestedMessage {
	if x != nil {
		return x.NestedMessage
	}
	return nil
}

func (x *ParentMessage) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *ParentMessage) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

type PointsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Points        []string               `protobuf:"bytes,1,rep,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PointsRequest) Reset() {
	*x = PointsRequest{}
	mi := &file_proto_helloworld_helloworld_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PointsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PointsRequest) ProtoMessage() {}

func (x *PointsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_helloworld_helloworld_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PointsRequest.ProtoReflect.Descriptor instead.
func (*PointsRequest) Descriptor() ([]byte, []int) {
	return file_proto_helloworld_helloworld_proto_rawDescGZIP(), []int{2}
}

func (x *PointsRequest) GetPoints() []string {
	if x != nil {
		return x.Points
	}
	return nil
}

// Points are represented as latitude-longitude pairs in the E7 representation
// (degrees multiplied by 10**7 and rounded to the nearest integer).
// Latitudes should be in the range +/- 90 degrees and longitude should be in
// the range +/- 180 degrees (inclusive).
type Point struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      int32                  `protobuf:"varint,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     int32                  `protobuf:"varint,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Point) Reset() {
	*x = Point{}
	mi := &file_proto_helloworld_helloworld_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Point) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Point) ProtoMessage() {}

func (x *Point) ProtoReflect() protoreflect.Message {
	mi := &file_proto_helloworld_helloworld_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Point.ProtoReflect.Descriptor instead.
func (*Point) Descriptor() ([]byte, []int) {
	return file_proto_helloworld_helloworld_proto_rawDescGZIP(), []int{3}
}

func (x *Point) GetLatitude() int32 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Point) GetLongitude() int32 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type RouteSummary struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The number of points received.
	PointCount int32 `protobuf:"varint,1,opt,name=point_count,json=pointCount,proto3" json:"point_count,omitempty"`
	// The duration of the traversal in seconds.
	ElapsedTime   int32 `protobuf:"varint,2,opt,name=elapsed_time,json=elapsedTime,proto3" json:"elapsed_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteSummary) Reset() {
	*x = RouteSummary{}
	mi := &file_proto_helloworld_helloworld_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteSummary) ProtoMessage() {}

func (x *RouteSummary) ProtoReflect() protoreflect.Message {
	mi := &file_proto_helloworld_helloworld_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteSummary.ProtoReflect.Descriptor instead.
func (*RouteSummary) Descriptor() ([]byte, []int) {
	return file_proto_helloworld_helloworld_proto_rawDescGZIP(), []int{4}
}

func (x *RouteSummary) GetPointCount() int32 {
	if x != nil {
		return x.PointCount
	}
	return 0
}

func (x *RouteSummary) GetElapsedTime() int32 {
	if x != nil {
		return x.ElapsedTime
	}
	return 0
}

var File_proto_helloworld_helloworld_proto protoreflect.FileDescriptor

const file_proto_helloworld_helloworld_proto_rawDesc = "" +
	"\n" +
	"!proto/helloworld/helloworld.proto\x12\n" +
	"helloworld\x1a\x1cgoogle/api/annotations.proto\x1a\x1anats/api/annotations.proto\x1a\x13models/models.proto\"8\n" +
	"\rNestedMessage\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\tR\x05orgId\x12\x10\n" +
	"\x03age\x18\x02 \x01(\x05R\x03age\"z\n" +
	"\rParentMessage\x12@\n" +
	"\x0enested_message\x18\x01 \x01(\v2\x19.helloworld.NestedMessageR\rnestedMessage\x12\x15\n" +
	"\x06org_id\x18\x02 \x01(\tR\x05orgId\x12\x10\n" +
	"\x03age\x18\x03 \x01(\x05R\x03age\"'\n" +
	"\rPointsRequest\x12\x16\n" +
	"\x06points\x18\x01 \x03(\tR\x06points\"A\n" +
	"\x05Point\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x05R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x05R\tlongitude\"R\n" +
	"\fRouteSummary\x12\x1f\n" +
	"\vpoint_count\x18\x01 \x01(\x05R\n" +
	"pointCount\x12!\n" +
	"\felapsed_time\x18\x02 \x01(\x05R\velapsedTime2\xcc\x02\n" +
	"\aGreeter\x12p\n" +
	"\bSayHello\x12\x14.models.HelloRequest\x1a\x12.models.HelloReply\":\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/v1/greeter/sayhello\x82\xe1\xfd\x97\x02\x15\n" +
	"\forg.${orgId}\x12\x05org.*\x12^\n" +
	"\fSayHelloAuth\x12\x14.models.HelloRequest\x1a\x12.models.HelloReply\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/v1/greeter/sayhello-auth\x12o\n" +
	"\x12SayHelloDownstream\x12\x14.models.HelloRequest\x1a\x12.models.HelloReply\"/\x82\xd3\xe4\x93\x02#:\x01*\"\x1e/v1/greeter/sayhellodownstream\x82\xe1\xfd\x97\x02\x002\xbb\x02\n" +
	"\bGreeter2\x12R\n" +
	"\bSayHello\x12\x14.models.HelloRequest\x1a\x13.models.HelloReply2\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/v2/example/echo\x12n\n" +
	"\rRequestPoints\x12\x19.helloworld.PointsRequest\x1a\x11.helloworld.Point\"-\x82\xd3\xe4\x93\x02':\x01*\"\"/v1/mystreamservice/request-points0\x01\x12k\n" +
	"\fStreamPoints\x12\x11.helloworld.Point\x1a\x18.helloworld.RouteSummary\",\x82\xd3\xe4\x93\x02&:\x01*\"!/v1/mystreamservice/upload-points(\x012\xee\x01\n" +
	"\x0fMyStreamService\x12n\n" +
	"\rRequestPoints\x12\x19.helloworld.PointsRequest\x1a\x11.helloworld.Point\"-\x82\xd3\xe4\x93\x02':\x01*\"\"/v1/mystreamservice/request-points0\x01\x12k\n" +
	"\fStreamPoints\x12\x11.helloworld.Point\x1a\x18.helloworld.RouteSummary\",\x82\xd3\xe4\x93\x02&:\x01*\"!/v1/mystreamservice/upload-points(\x01Bp\n" +
	"\x1bio.grpc.examples.helloworldB\x0fHelloWorldProtoP\x01Z>github.com/fluffy-bunny/fluffycore/proto/helloworld/helloworldb\x06proto3"

var (
	file_proto_helloworld_helloworld_proto_rawDescOnce sync.Once
	file_proto_helloworld_helloworld_proto_rawDescData []byte
)

func file_proto_helloworld_helloworld_proto_rawDescGZIP() []byte {
	file_proto_helloworld_helloworld_proto_rawDescOnce.Do(func() {
		file_proto_helloworld_helloworld_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_helloworld_helloworld_proto_rawDesc), len(file_proto_helloworld_helloworld_proto_rawDesc)))
	})
	return file_proto_helloworld_helloworld_proto_rawDescData
}

var file_proto_helloworld_helloworld_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_helloworld_helloworld_proto_goTypes = []any{
	(*NestedMessage)(nil),       // 0: helloworld.NestedMessage
	(*ParentMessage)(nil),       // 1: helloworld.ParentMessage
	(*PointsRequest)(nil),       // 2: helloworld.PointsRequest
	(*Point)(nil),               // 3: helloworld.Point
	(*RouteSummary)(nil),        // 4: helloworld.RouteSummary
	(*models.HelloRequest)(nil), // 5: models.HelloRequest
	(*models.HelloReply)(nil),   // 6: models.HelloReply
	(*models.HelloReply2)(nil),  // 7: models.HelloReply2
}
var file_proto_helloworld_helloworld_proto_depIdxs = []int32{
	0, // 0: helloworld.ParentMessage.nested_message:type_name -> helloworld.NestedMessage
	5, // 1: helloworld.Greeter.SayHello:input_type -> models.HelloRequest
	5, // 2: helloworld.Greeter.SayHelloAuth:input_type -> models.HelloRequest
	5, // 3: helloworld.Greeter.SayHelloDownstream:input_type -> models.HelloRequest
	5, // 4: helloworld.Greeter2.SayHello:input_type -> models.HelloRequest
	2, // 5: helloworld.Greeter2.RequestPoints:input_type -> helloworld.PointsRequest
	3, // 6: helloworld.Greeter2.StreamPoints:input_type -> helloworld.Point
	2, // 7: helloworld.MyStreamService.RequestPoints:input_type -> helloworld.PointsRequest
	3, // 8: helloworld.MyStreamService.StreamPoints:input_type -> helloworld.Point
	6, // 9: helloworld.Greeter.SayHello:output_type -> models.HelloReply
	6, // 10: helloworld.Greeter.SayHelloAuth:output_type -> models.HelloReply
	6, // 11: helloworld.Greeter.SayHelloDownstream:output_type -> models.HelloReply
	7, // 12: helloworld.Greeter2.SayHello:output_type -> models.HelloReply2
	3, // 13: helloworld.Greeter2.RequestPoints:output_type -> helloworld.Point
	4, // 14: helloworld.Greeter2.StreamPoints:output_type -> helloworld.RouteSummary
	3, // 15: helloworld.MyStreamService.RequestPoints:output_type -> helloworld.Point
	4, // 16: helloworld.MyStreamService.StreamPoints:output_type -> helloworld.RouteSummary
	9, // [9:17] is the sub-list for method output_type
	1, // [1:9] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_helloworld_helloworld_proto_init() }
func file_proto_helloworld_helloworld_proto_init() {
	if File_proto_helloworld_helloworld_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_helloworld_helloworld_proto_rawDesc), len(file_proto_helloworld_helloworld_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_proto_helloworld_helloworld_proto_goTypes,
		DependencyIndexes: file_proto_helloworld_helloworld_proto_depIdxs,
		MessageInfos:      file_proto_helloworld_helloworld_proto_msgTypes,
	}.Build()
	File_proto_helloworld_helloworld_proto = out.File
	file_proto_helloworld_helloworld_proto_goTypes = nil
	file_proto_helloworld_helloworld_proto_depIdxs = nil
}
