// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.17.3
// source: proto/helloworld/helloworld.proto

package helloworld

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GreeterClient is the client API for Greeter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GreeterClient interface {
	// Sends a greeting
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type greeterClient struct {
	cc grpc.ClientConnInterface
}

func NewGreeterClient(cc grpc.ClientConnInterface) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/helloworld.Greeter/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GreeterServer is the server API for Greeter service.
// All implementations must embed UnimplementedGreeterServer
// for forward compatibility
type GreeterServer interface {
	// Sends a greeting
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	mustEmbedUnimplementedGreeterServer()
}

// UnimplementedGreeterServer must be embedded to have forward compatible implementations.
type UnimplementedGreeterServer struct {
}

func (UnimplementedGreeterServer) SayHello(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedGreeterServer) mustEmbedUnimplementedGreeterServer() {}

// UnsafeGreeterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GreeterServer will
// result in compilation errors.
type UnsafeGreeterServer interface {
	mustEmbedUnimplementedGreeterServer()
}

func RegisterGreeterServer(s grpc.ServiceRegistrar, srv GreeterServer) {
	s.RegisterService(&Greeter_ServiceDesc, srv)
}

func _Greeter_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/helloworld.Greeter/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Greeter_ServiceDesc is the grpc.ServiceDesc for Greeter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Greeter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "helloworld.Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Greeter_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/helloworld/helloworld.proto",
}

// Greeter2Client is the client API for Greeter2 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type Greeter2Client interface {
	// Sends a greeting
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply2, error)
}

type greeter2Client struct {
	cc grpc.ClientConnInterface
}

func NewGreeter2Client(cc grpc.ClientConnInterface) Greeter2Client {
	return &greeter2Client{cc}
}

func (c *greeter2Client) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply2, error) {
	out := new(HelloReply2)
	err := c.cc.Invoke(ctx, "/helloworld.Greeter2/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Greeter2Server is the server API for Greeter2 service.
// All implementations must embed UnimplementedGreeter2Server
// for forward compatibility
type Greeter2Server interface {
	// Sends a greeting
	SayHello(context.Context, *HelloRequest) (*HelloReply2, error)
	mustEmbedUnimplementedGreeter2Server()
}

// UnimplementedGreeter2Server must be embedded to have forward compatible implementations.
type UnimplementedGreeter2Server struct {
}

func (UnimplementedGreeter2Server) SayHello(context.Context, *HelloRequest) (*HelloReply2, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedGreeter2Server) mustEmbedUnimplementedGreeter2Server() {}

// UnsafeGreeter2Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to Greeter2Server will
// result in compilation errors.
type UnsafeGreeter2Server interface {
	mustEmbedUnimplementedGreeter2Server()
}

func RegisterGreeter2Server(s grpc.ServiceRegistrar, srv Greeter2Server) {
	s.RegisterService(&Greeter2_ServiceDesc, srv)
}

func _Greeter2_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Greeter2Server).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/helloworld.Greeter2/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Greeter2Server).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Greeter2_ServiceDesc is the grpc.ServiceDesc for Greeter2 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Greeter2_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "helloworld.Greeter2",
	HandlerType: (*Greeter2Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Greeter2_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/helloworld/helloworld.proto",
}

// EdgeControlServiceClient is the client API for EdgeControlService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EdgeControlServiceClient interface {
	// RequestPoints
	// Request: Unary
	// Response: Streaming
	RequestPoints(ctx context.Context, in *PointsRequest, opts ...grpc.CallOption) (EdgeControlService_RequestPointsClient, error)
	// Accepts a stream of Points on a route being traversed, returning a
	// RouteSummary when traversal is completed.
	StreamPoints(ctx context.Context, opts ...grpc.CallOption) (EdgeControlService_StreamPointsClient, error)
}

type edgeControlServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEdgeControlServiceClient(cc grpc.ClientConnInterface) EdgeControlServiceClient {
	return &edgeControlServiceClient{cc}
}

func (c *edgeControlServiceClient) RequestPoints(ctx context.Context, in *PointsRequest, opts ...grpc.CallOption) (EdgeControlService_RequestPointsClient, error) {
	stream, err := c.cc.NewStream(ctx, &EdgeControlService_ServiceDesc.Streams[0], "/helloworld.EdgeControlService/RequestPoints", opts...)
	if err != nil {
		return nil, err
	}
	x := &edgeControlServiceRequestPointsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type EdgeControlService_RequestPointsClient interface {
	Recv() (*Point, error)
	grpc.ClientStream
}

type edgeControlServiceRequestPointsClient struct {
	grpc.ClientStream
}

func (x *edgeControlServiceRequestPointsClient) Recv() (*Point, error) {
	m := new(Point)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *edgeControlServiceClient) StreamPoints(ctx context.Context, opts ...grpc.CallOption) (EdgeControlService_StreamPointsClient, error) {
	stream, err := c.cc.NewStream(ctx, &EdgeControlService_ServiceDesc.Streams[1], "/helloworld.EdgeControlService/StreamPoints", opts...)
	if err != nil {
		return nil, err
	}
	x := &edgeControlServiceStreamPointsClient{stream}
	return x, nil
}

type EdgeControlService_StreamPointsClient interface {
	Send(*Point) error
	CloseAndRecv() (*RouteSummary, error)
	grpc.ClientStream
}

type edgeControlServiceStreamPointsClient struct {
	grpc.ClientStream
}

func (x *edgeControlServiceStreamPointsClient) Send(m *Point) error {
	return x.ClientStream.SendMsg(m)
}

func (x *edgeControlServiceStreamPointsClient) CloseAndRecv() (*RouteSummary, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(RouteSummary)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// EdgeControlServiceServer is the server API for EdgeControlService service.
// All implementations must embed UnimplementedEdgeControlServiceServer
// for forward compatibility
type EdgeControlServiceServer interface {
	// RequestPoints
	// Request: Unary
	// Response: Streaming
	RequestPoints(*PointsRequest, EdgeControlService_RequestPointsServer) error
	// Accepts a stream of Points on a route being traversed, returning a
	// RouteSummary when traversal is completed.
	StreamPoints(EdgeControlService_StreamPointsServer) error
	mustEmbedUnimplementedEdgeControlServiceServer()
}

// UnimplementedEdgeControlServiceServer must be embedded to have forward compatible implementations.
type UnimplementedEdgeControlServiceServer struct {
}

func (UnimplementedEdgeControlServiceServer) RequestPoints(*PointsRequest, EdgeControlService_RequestPointsServer) error {
	return status.Errorf(codes.Unimplemented, "method RequestPoints not implemented")
}
func (UnimplementedEdgeControlServiceServer) StreamPoints(EdgeControlService_StreamPointsServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamPoints not implemented")
}
func (UnimplementedEdgeControlServiceServer) mustEmbedUnimplementedEdgeControlServiceServer() {}

// UnsafeEdgeControlServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EdgeControlServiceServer will
// result in compilation errors.
type UnsafeEdgeControlServiceServer interface {
	mustEmbedUnimplementedEdgeControlServiceServer()
}

func RegisterEdgeControlServiceServer(s grpc.ServiceRegistrar, srv EdgeControlServiceServer) {
	s.RegisterService(&EdgeControlService_ServiceDesc, srv)
}

func _EdgeControlService_RequestPoints_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PointsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EdgeControlServiceServer).RequestPoints(m, &edgeControlServiceRequestPointsServer{stream})
}

type EdgeControlService_RequestPointsServer interface {
	Send(*Point) error
	grpc.ServerStream
}

type edgeControlServiceRequestPointsServer struct {
	grpc.ServerStream
}

func (x *edgeControlServiceRequestPointsServer) Send(m *Point) error {
	return x.ServerStream.SendMsg(m)
}

func _EdgeControlService_StreamPoints_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(EdgeControlServiceServer).StreamPoints(&edgeControlServiceStreamPointsServer{stream})
}

type EdgeControlService_StreamPointsServer interface {
	SendAndClose(*RouteSummary) error
	Recv() (*Point, error)
	grpc.ServerStream
}

type edgeControlServiceStreamPointsServer struct {
	grpc.ServerStream
}

func (x *edgeControlServiceStreamPointsServer) SendAndClose(m *RouteSummary) error {
	return x.ServerStream.SendMsg(m)
}

func (x *edgeControlServiceStreamPointsServer) Recv() (*Point, error) {
	m := new(Point)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// EdgeControlService_ServiceDesc is the grpc.ServiceDesc for EdgeControlService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EdgeControlService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "helloworld.EdgeControlService",
	HandlerType: (*EdgeControlServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RequestPoints",
			Handler:       _EdgeControlService_RequestPoints_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamPoints",
			Handler:       _EdgeControlService_StreamPoints_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "proto/helloworld/helloworld.proto",
}
