// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: nats/api/handler.proto

package annotations

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HandlerRule struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ParameterizedToken string                 `protobuf:"bytes,1,opt,name=parameterized_token,json=parameterizedToken,proto3" json:"parameterized_token,omitempty"`
	WildcardToken      string                 `protobuf:"bytes,2,opt,name=wildcard_token,json=wildcardToken,proto3" json:"wildcard_token,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *HandlerRule) Reset() {
	*x = HandlerRule{}
	mi := &file_nats_api_handler_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandlerRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandlerRule) ProtoMessage() {}

func (x *HandlerRule) ProtoReflect() protoreflect.Message {
	mi := &file_nats_api_handler_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandlerRule.ProtoReflect.Descriptor instead.
func (*HandlerRule) Descriptor() ([]byte, []int) {
	return file_nats_api_handler_proto_rawDescGZIP(), []int{0}
}

func (x *HandlerRule) GetParameterizedToken() string {
	if x != nil {
		return x.ParameterizedToken
	}
	return ""
}

func (x *HandlerRule) GetWildcardToken() string {
	if x != nil {
		return x.WildcardToken
	}
	return ""
}

var File_nats_api_handler_proto protoreflect.FileDescriptor

const file_nats_api_handler_proto_rawDesc = "" +
	"\n" +
	"\x16nats/api/handler.proto\x12\bnats.api\"e\n" +
	"\vHandlerRule\x12/\n" +
	"\x13parameterized_token\x18\x01 \x01(\tR\x12parameterizedToken\x12%\n" +
	"\x0ewildcard_token\x18\x02 \x01(\tR\rwildcardTokenBm\n" +
	"\fcom.nats.apiB\fHandlerProtoP\x01ZCgithub.com/fluffy-bunny/fluffycore/nats/api/annotations;annotations\xf8\x01\x01\xa2\x02\x04NAPIb\x06proto3"

var (
	file_nats_api_handler_proto_rawDescOnce sync.Once
	file_nats_api_handler_proto_rawDescData []byte
)

func file_nats_api_handler_proto_rawDescGZIP() []byte {
	file_nats_api_handler_proto_rawDescOnce.Do(func() {
		file_nats_api_handler_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nats_api_handler_proto_rawDesc), len(file_nats_api_handler_proto_rawDesc)))
	})
	return file_nats_api_handler_proto_rawDescData
}

var file_nats_api_handler_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_nats_api_handler_proto_goTypes = []any{
	(*HandlerRule)(nil), // 0: nats.api.HandlerRule
}
var file_nats_api_handler_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_nats_api_handler_proto_init() }
func file_nats_api_handler_proto_init() {
	if File_nats_api_handler_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nats_api_handler_proto_rawDesc), len(file_nats_api_handler_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_nats_api_handler_proto_goTypes,
		DependencyIndexes: file_nats_api_handler_proto_depIdxs,
		MessageInfos:      file_nats_api_handler_proto_msgTypes,
	}.Build()
	File_nats_api_handler_proto = out.File
	file_nats_api_handler_proto_goTypes = nil
	file_nats_api_handler_proto_depIdxs = nil
}
