// Code generated by protoc-gen-go-fluffycore-di. DO NOT EDIT.
// Code generated grpcGateway

package someservice

import (
	context "context"
	fluffy_dozm_di "github.com/fluffy-bunny/fluffy-dozm-di"
	endpoint "github.com/fluffy-bunny/fluffycore/contracts/endpoint"
	dicontext "github.com/fluffy-bunny/fluffycore/middleware/dicontext"
	runtime "github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	grpc "google.golang.org/grpc"
)

// ISomeServiceServer defines the grpc server
type ISomeServiceServer interface {
	SomeServiceServer
}

type UnimplementedSomeServiceServerEndpointRegistration struct {
}

func (UnimplementedSomeServiceServerEndpointRegistration) RegisterHandler(gwmux *runtime.ServeMux, conn *grpc.ClientConn) {
}

// someserviceServer defines the grpc server truct
type someserviceServer struct {
	UnimplementedSomeServiceServer
	UnimplementedSomeServiceServerEndpointRegistration
}

// Register the server with grpc
func (srv *someserviceServer) RegisterHandler(gwmux *runtime.ServeMux, conn *grpc.ClientConn) {
	RegisterSomeServiceHandler(context.Background(), gwmux, conn)
}

// Register the server with grpc
func (srv *someserviceServer) Register(s *grpc.Server) {
	RegisterSomeServiceServer(s, srv)
}

// AddSomeServiceServer adds the fluffycore aware grpc server
func AddSomeServiceServer[T ISomeServiceServer](cb fluffy_dozm_di.ContainerBuilder, ctor any) {
	fluffy_dozm_di.AddSingleton[endpoint.IEndpointRegistration](cb, func() endpoint.IEndpointRegistration {
		return &someserviceServer{}
	})
	fluffy_dozm_di.AddScoped[ISomeServiceServer](cb, ctor)
}

// SayHello...
func (s *someserviceServer) SayHello(ctx context.Context, request *HelloRequest) (*HelloReply, error) {
	requestContainer := dicontext.GetRequestContainer(ctx)
	downstreamService := fluffy_dozm_di.Get[ISomeServiceServer](requestContainer)
	return downstreamService.SayHello(ctx, request)
}

// ISomeService2Server defines the grpc server
type ISomeService2Server interface {
	SomeService2Server
}

type UnimplementedSomeService2ServerEndpointRegistration struct {
}

func (UnimplementedSomeService2ServerEndpointRegistration) RegisterHandler(gwmux *runtime.ServeMux, conn *grpc.ClientConn) {
}

// someservice2Server defines the grpc server truct
type someservice2Server struct {
	UnimplementedSomeService2Server
	UnimplementedSomeService2ServerEndpointRegistration
}

// Register the server with grpc
func (srv *someservice2Server) RegisterHandler(gwmux *runtime.ServeMux, conn *grpc.ClientConn) {
	RegisterSomeService2Handler(context.Background(), gwmux, conn)
}

// Register the server with grpc
func (srv *someservice2Server) Register(s *grpc.Server) {
	RegisterSomeService2Server(s, srv)
}

// AddSomeService2Server adds the fluffycore aware grpc server
func AddSomeService2Server[T ISomeService2Server](cb fluffy_dozm_di.ContainerBuilder, ctor any) {
	fluffy_dozm_di.AddSingleton[endpoint.IEndpointRegistration](cb, func() endpoint.IEndpointRegistration {
		return &someservice2Server{}
	})
	fluffy_dozm_di.AddScoped[ISomeService2Server](cb, ctor)
}

// SayHello...
func (s *someservice2Server) SayHello(ctx context.Context, request *HelloRequest) (*HelloReply2, error) {
	requestContainer := dicontext.GetRequestContainer(ctx)
	downstreamService := fluffy_dozm_di.Get[ISomeService2Server](requestContainer)
	return downstreamService.SayHello(ctx, request)
}
