// Copyright 2015 gRPC authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/someservice/someservice.proto

package someservice

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message containing the user's name.
type HelloRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloRequest) Reset() {
	*x = HelloRequest{}
	mi := &file_proto_someservice_someservice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest) ProtoMessage() {}

func (x *HelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_someservice_someservice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return file_proto_someservice_someservice_proto_rawDescGZIP(), []int{0}
}

func (x *HelloRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// The response message containing the greetings
type HelloReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloReply) Reset() {
	*x = HelloReply{}
	mi := &file_proto_someservice_someservice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloReply) ProtoMessage() {}

func (x *HelloReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_someservice_someservice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloReply.ProtoReflect.Descriptor instead.
func (*HelloReply) Descriptor() ([]byte, []int) {
	return file_proto_someservice_someservice_proto_rawDescGZIP(), []int{1}
}

func (x *HelloReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type HelloReply2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloReply2) Reset() {
	*x = HelloReply2{}
	mi := &file_proto_someservice_someservice_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloReply2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloReply2) ProtoMessage() {}

func (x *HelloReply2) ProtoReflect() protoreflect.Message {
	mi := &file_proto_someservice_someservice_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloReply2.ProtoReflect.Descriptor instead.
func (*HelloReply2) Descriptor() ([]byte, []int) {
	return file_proto_someservice_someservice_proto_rawDescGZIP(), []int{2}
}

func (x *HelloReply2) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_someservice_someservice_proto protoreflect.FileDescriptor

const file_proto_someservice_someservice_proto_rawDesc = "" +
	"\n" +
	"#proto/someservice/someservice.proto\x12\vsomeservice\x1a\x1cgoogle/api/annotations.proto\"\"\n" +
	"\fHelloRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"&\n" +
	"\n" +
	"HelloReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"'\n" +
	"\vHelloReply2\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2n\n" +
	"\vSomeService\x12_\n" +
	"\bSayHello\x12\x19.someservice.HelloRequest\x1a\x17.someservice.HelloReply\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/v1/someservice/echo2p\n" +
	"\fSomeService2\x12`\n" +
	"\bSayHello\x12\x19.someservice.HelloRequest\x1a\x18.someservice.HelloReply2\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/v2/someservice/echoBk\n" +
	"\x1cio.grpc.examples.someserviceB\x10SomeServiceProtoP\x01Z7google.golang.org/grpc/examples/someservice/someserviceb\x06proto3"

var (
	file_proto_someservice_someservice_proto_rawDescOnce sync.Once
	file_proto_someservice_someservice_proto_rawDescData []byte
)

func file_proto_someservice_someservice_proto_rawDescGZIP() []byte {
	file_proto_someservice_someservice_proto_rawDescOnce.Do(func() {
		file_proto_someservice_someservice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_someservice_someservice_proto_rawDesc), len(file_proto_someservice_someservice_proto_rawDesc)))
	})
	return file_proto_someservice_someservice_proto_rawDescData
}

var file_proto_someservice_someservice_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_someservice_someservice_proto_goTypes = []any{
	(*HelloRequest)(nil), // 0: someservice.HelloRequest
	(*HelloReply)(nil),   // 1: someservice.HelloReply
	(*HelloReply2)(nil),  // 2: someservice.HelloReply2
}
var file_proto_someservice_someservice_proto_depIdxs = []int32{
	0, // 0: someservice.SomeService.SayHello:input_type -> someservice.HelloRequest
	0, // 1: someservice.SomeService2.SayHello:input_type -> someservice.HelloRequest
	1, // 2: someservice.SomeService.SayHello:output_type -> someservice.HelloReply
	2, // 3: someservice.SomeService2.SayHello:output_type -> someservice.HelloReply2
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_someservice_someservice_proto_init() }
func file_proto_someservice_someservice_proto_init() {
	if File_proto_someservice_someservice_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_someservice_someservice_proto_rawDesc), len(file_proto_someservice_someservice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_someservice_someservice_proto_goTypes,
		DependencyIndexes: file_proto_someservice_someservice_proto_depIdxs,
		MessageInfos:      file_proto_someservice_someservice_proto_msgTypes,
	}.Build()
	File_proto_someservice_someservice_proto = out.File
	file_proto_someservice_someservice_proto_goTypes = nil
	file_proto_someservice_someservice_proto_depIdxs = nil
}
