// Code generated by protoc-gen-go-fluffycore-di. DO NOT EDIT.
// Code generated grpcGateway

package someservice

import (
	context "context"
	fluffy_dozm_di "github.com/fluffy-bunny/fluffy-dozm-di"
	endpoint "github.com/fluffy-bunny/fluffycore/contracts/endpoint"
	dicontext "github.com/fluffy-bunny/fluffycore/middleware/dicontext"
	runtime "github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	grpc "google.golang.org/grpc"
)

// IFluffyCoreSomeServiceServer defines the grpc server
type IFluffyCoreSomeServiceServer interface {
	SomeServiceServer
}

type UnimplementedFluffyCoreSomeServiceServerEndpointRegistration struct {
}

func (UnimplementedFluffyCoreSomeServiceServerEndpointRegistration) RegisterFluffyCoreHandler(gwmux *runtime.ServeMux, conn *grpc.ClientConn) {
}

// SomeServiceFluffyCoreServer defines the grpc server truct
type SomeServiceFluffyCoreServer struct {
	UnimplementedSomeServiceServer
	UnimplementedFluffyCoreSomeServiceServerEndpointRegistration
}

// RegisterFluffyCoreGRPCService the server with grpc
func (srv *SomeServiceFluffyCoreServer) RegisterFluffyCoreGRPCService(s *grpc.Server) {
	RegisterSomeServiceServer(s, srv)
}

// AddSomeServiceServerWithExternalRegistration adds the fluffycore aware grpc server and external registration service.  Mainly used for grpc-gateway
func AddSomeServiceServerWithExternalRegistration(cb fluffy_dozm_di.ContainerBuilder, ctor any, register func() endpoint.IEndpointRegistration) {
	fluffy_dozm_di.AddSingleton[endpoint.IEndpointRegistration](cb, register)
	fluffy_dozm_di.AddScoped[IFluffyCoreSomeServiceServer](cb, ctor)
}

// AddSomeServiceServer adds the fluffycore aware grpc server
func AddSomeServiceServer(cb fluffy_dozm_di.ContainerBuilder, ctor any) {
	AddSomeServiceServerWithExternalRegistration(cb, ctor, func() endpoint.IEndpointRegistration {
		return &SomeServiceFluffyCoreServer{}
	})
}

// SayHello...
func (s *SomeServiceFluffyCoreServer) SayHello(ctx context.Context, request *HelloRequest) (*HelloReply, error) {
	requestContainer := dicontext.GetRequestContainer(ctx)
	downstreamService := fluffy_dozm_di.Get[IFluffyCoreSomeServiceServer](requestContainer)
	return downstreamService.SayHello(ctx, request)
}

// IFluffyCoreSomeService2Server defines the grpc server
type IFluffyCoreSomeService2Server interface {
	SomeService2Server
}

type UnimplementedFluffyCoreSomeService2ServerEndpointRegistration struct {
}

func (UnimplementedFluffyCoreSomeService2ServerEndpointRegistration) RegisterFluffyCoreHandler(gwmux *runtime.ServeMux, conn *grpc.ClientConn) {
}

// SomeService2FluffyCoreServer defines the grpc server truct
type SomeService2FluffyCoreServer struct {
	UnimplementedSomeService2Server
	UnimplementedFluffyCoreSomeService2ServerEndpointRegistration
}

// RegisterFluffyCoreGRPCService the server with grpc
func (srv *SomeService2FluffyCoreServer) RegisterFluffyCoreGRPCService(s *grpc.Server) {
	RegisterSomeService2Server(s, srv)
}

// AddSomeService2ServerWithExternalRegistration adds the fluffycore aware grpc server and external registration service.  Mainly used for grpc-gateway
func AddSomeService2ServerWithExternalRegistration(cb fluffy_dozm_di.ContainerBuilder, ctor any, register func() endpoint.IEndpointRegistration) {
	fluffy_dozm_di.AddSingleton[endpoint.IEndpointRegistration](cb, register)
	fluffy_dozm_di.AddScoped[IFluffyCoreSomeService2Server](cb, ctor)
}

// AddSomeService2Server adds the fluffycore aware grpc server
func AddSomeService2Server(cb fluffy_dozm_di.ContainerBuilder, ctor any) {
	AddSomeService2ServerWithExternalRegistration(cb, ctor, func() endpoint.IEndpointRegistration {
		return &SomeService2FluffyCoreServer{}
	})
}

// SayHello...
func (s *SomeService2FluffyCoreServer) SayHello(ctx context.Context, request *HelloRequest) (*HelloReply2, error) {
	requestContainer := dicontext.GetRequestContainer(ctx)
	downstreamService := fluffy_dozm_di.Get[IFluffyCoreSomeService2Server](requestContainer)
	return downstreamService.SayHello(ctx, request)
}
