// Copyright 2015 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: nats/api/annotations.proto

package annotations

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var file_nats_api_annotations_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*HandlerRule)(nil),
		Field:         73395728,
		Name:          "nats.api.handler",
		Tag:           "bytes,73395728,opt,name=handler",
		Filename:      "nats/api/annotations.proto",
	},
}

// Extension fields to descriptorpb.MethodOptions.
var (
	// See `HandlerRule`.
	//
	// optional nats.api.HandlerRule handler = 73395728;
	E_Handler = &file_nats_api_annotations_proto_extTypes[0]
)

var File_nats_api_annotations_proto protoreflect.FileDescriptor

const file_nats_api_annotations_proto_rawDesc = "" +
	"\n" +
	"\x1anats/api/annotations.proto\x12\bnats.api\x1a\x16nats/api/handler.proto\x1a google/protobuf/descriptor.proto:R\n" +
	"\ahandler\x12\x1e.google.protobuf.MethodOptions\x18\x90\xdc\xff\" \x01(\v2\x15.nats.api.HandlerRuleR\ahandlerBn\n" +
	"\fcom.nats.apiB\x10AnnotationsProtoP\x01ZCgithub.com/fluffy-bunny/fluffycore/nats/api/annotations;annotations\xa2\x02\x04NAPIb\x06proto3"

var file_nats_api_annotations_proto_goTypes = []any{
	(*descriptorpb.MethodOptions)(nil), // 0: google.protobuf.MethodOptions
	(*HandlerRule)(nil),                // 1: nats.api.HandlerRule
}
var file_nats_api_annotations_proto_depIdxs = []int32{
	0, // 0: nats.api.handler:extendee -> google.protobuf.MethodOptions
	1, // 1: nats.api.handler:type_name -> nats.api.HandlerRule
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	1, // [1:2] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_nats_api_annotations_proto_init() }
func file_nats_api_annotations_proto_init() {
	if File_nats_api_annotations_proto != nil {
		return
	}
	file_nats_api_handler_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nats_api_annotations_proto_rawDesc), len(file_nats_api_annotations_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_nats_api_annotations_proto_goTypes,
		DependencyIndexes: file_nats_api_annotations_proto_depIdxs,
		ExtensionInfos:    file_nats_api_annotations_proto_extTypes,
	}.Build()
	File_nats_api_annotations_proto = out.File
	file_nats_api_annotations_proto_goTypes = nil
	file_nats_api_annotations_proto_depIdxs = nil
}
